config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :sessions, only: [:create, :destroy]
  resources :users, only: [:create, :show] do
  	resources :relationships, only: [:create, :destroy]
  end
  resources :rooms, only: [:create, :update, :show, :destroy]
  resources :games, only: [:create, :destroy]
  
  post "/games/input" => "games#input", as: "input"

  post "/users/search" => "users#search", as: "search"

  get "/sign_up" => "users#new", as: "sign_up"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  def self.get_domains
    url = "https://od-api.oxforddictionaries.com/api/v1/domains/en"
    response = open(url, "app_id" => ENV["APP_ID"], "app_key" => ENV["APP_KEY"]).read
    json_data = JSON.load(response)["results"]
    domains = []
    json_data.each do |domain|
      if !(domain[1]["en"].scan(/\s/).any?)
        domains << domain[1]["en"]
      end
    end
    domains
  end

  def self.get_words(category)
  	url = "https://od-api.oxforddictionaries.com:443/api/v1/wordlist/en/domains=#{category}"
  	response = open(url, "app_id" => ENV["APP_ID"], "app_key" => ENV["APP_KEY"]).read
  	json_data = JSON.load(response)["results"]
  	words = []
  	json_data.each do |result|
    	  if result["word"] =~ /[a-z]+\s*[a-z]*/ && result["word"].length >= 6 && result["word"].length <= 10
      	words << result["word"]
    	  end
  	end
  	words
  end

  def self.check_for_special_char(word)
    @space, @quote, @dash, @comma = nil, nil, nil, nil
  	word.scan(/\s/) { |space| @space = [word.index(space), " "] }
  	word.scan(/'/) { |quote| @quote = [word.index(quote), "'"] }
  	word.scan(/-/) { |dash| @dash = [word.index(dash), "-"] }
    word.scan(/,/) { |comma| @comma = [word.index(comma), ","] }
  	special_char = [@space, @quote, @dash, @comma]
  	special_char.any? { |x| !(x.nil?) } ? special_char : false
  end

  def self.generate_blanks(selected_word)
	  blanks = []
  	selected_word.size.times { blanks << "_" }
    check = Game.check_for_special_char(selected_word)
  	  if check
        check.each do |x|
        	if x
        	  blanks[x[0]] = x[1]
          end
        end
  	  end
  	blanks
  end

  def self.replace(blanks, word, letter)
    position = word.indices(letter)
      position.each do |pos|
        blanks[pos] = letter.upcase
      end
    blanks
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
  validates :user_id, presence: true
  validates :friend_id, presence: true

  def self.friends?(user, friend_id)
  	user.relationships.where(friend_id: friend_id).exists?
  end
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :owner, class_name: "User"
	belongs_to :visitor, class_name: "User", optional: true
end

app/models/user.rb
class User < ApplicationRecord
	include Filterable

	has_many :relationships, class_name: "Relationship", foreign_key: "user_id", dependent: :destroy
	has_many :friends, through: :relationships, source: :friend
	has_one :room, class_name: "Room", foreign_key: "owner_id", dependent: :destroy
	has_many :visitors, through: :rooms, source: :visitor

	validates :email, uniqueness: true, format: { with: /(^([a-z]*\s*)*\<*([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\>*$)/i }
	validates :password, format: { with: /^(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$/,
								   multiline: true }

	scope :search_name, -> (name) { where("name ILIKE ?", "%#{name}%") }
	
	has_secure_password

	enum role: [:visitor, :owner]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  require 'open-uri'

  private

  def current_user
    @_current_user ||= session[:user_id] &&
      User.find_by(id: session[:user_id])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def create
		@game = Game.new(owner_id: params["game"]["owner_id"])
		@game.visitor_id = params["game"]["visitor_id"]
		@game.domain = params["category"]
		@game.word = Game.get_words(params["category"]).sample
		if @game.save
			@wrong = Array.new
			@room = current_user.room
			render "rooms/show"
		else
			redirect_to root_path
		end
	end

	def input
		@game = Game.find(params[:game_id])
		@mistake = params[:mistake].to_i
		@wrong = params[:wrong]
		if @game.word.scan(params[:input]).any?
			@word = Game.replace(params[:word], @game.word, params[:input])
		else
			@wrong << params[:input].upcase
			@word = params[:word]
			@mistake += 1
		end
		@room = current_user.room
		render "rooms/show"
	end

	private

	def game_params
		params.require(:game).permit(:owner_id, :visitor_id, :domain, :word)
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  	current_user.relationships.create(friend_id: params[:user_id])
  	redirect_to root_path
  end


  def destroy
  	@relationship = current_user.relationships.find_by(friend_id: params[:user_id])
  	@relationship.destroy
  	redirect_to root_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
  	@room = Room.new(owner_id: current_user.id)
    current_user.role = 1
  	if @room.save && current_user.save(validate: false)
  		redirect_to room_path(@room.id)
  	else
  		redirect_to root_path
  	end
  end

  def update
  	current_user.room.update(visitor_id: params[:friend_id])
    @room = current_user.room
    visitor = User.find(params[:friend_id])
    respond_to do |format|
      format.json { render json: visitor }
    end
  end

  def show
    @room = current_user.room
    @game = Game.new
  end

  def destroy
  	@room = current_user.room.destroy
    current_user.role = 0
    current_user.save
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	@user = User.find_by(email: params[:user][:email])
	if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_url
    end
  end

  def new
  	@user = User.new
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path
		else
			flash[:alert] = "Bad email or password"
			render "sessions/new"
		end
	end

	def show
		@user = current_user
	end

	def new
		@user = User.new
	end

	def search
		@user = current_user
		@users = User.filter(params.slice(:search_name))
		render "welcome/index"
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include UsersHelper

  def index
  	if logged_in?
		@user = User.find_by(id: session[:user_id])
	else
		@user = User.new
		render "sessions/new"
	end

	if !@user.room.nil?
		@room = @user.room
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangman</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<div id="flash">
   	  <% flash.each do |key, value| %>
    	<div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
  	</div>

    <%= yield %>
  </body>
</html>

app/views/rooms/show.html.erb
<div class="p-3 mb-2 bg-light text-dark">

<%= render partial: '/welcome/navbar' %>

<%= content_tag :div, class:"room_info", data: {room: @room.id.to_s} do %>
<% end %>

<div class="container", style="background: white; width: 90%; height: 100%;">
  <div class="row">
    <div class="col-md-8 col-md-offset-1 col-sm-6 col-sm-offset-1">
		<h3>You are in Room <%= @room.id %></h3>
		<h5>Player 1: <%= @room.owner.name %></h5>

	  <% if @room.visitor.nil? %>
		<h5>Player 2: <span id="target">nil</span></h5>
	  <% else %>
		<h5>Player 2: <%= @room.visitor.name %></h5>
	  <% end %>

		<%= button_to "Leave Room", room_path(@room.id), method: :delete, class:"btn btn-info", style:"float: left;" %>

		<%= button_to "New Game", room_path(@room.id), method: :get, class:"btn btn-success", style:"float: left; margin-left: 10px;" %>

		<% @domains = Game.get_domains %>

		<div style="margin-top: 100px;">
			<%= form_for @game, url: games_path do |f| %>
				<h3><%= f.label :Category %></h3>
				<% if @game.domain.nil? %>
					<%= select_tag "category", options_for_select(@domains), prompt: 'Select', style:"float: left; height: 34px;" %>

					<%= f.hidden_field :owner_id, value: @room.owner_id %>
					<%= f.hidden_field :visitor_id, value: @room.visitor_id %>

					<%= f.submit "Go", :class => "btn btn-danger", style:"float: left;"%>
				<% else %>
					<%= @game.domain %>
				<% end %>
			<% end %>
		</div>
    </div>

    <div class="col-md-3 col-sm-5">
		<%= render partial: '/welcome/friends' %>
    </div>
  </div>

  <div class="row">
  	<div class="col-md-8">
  		<div align="center", style="margin-top: 70px;">
			<% if !@game.id.nil? %>

			  <% if @word.nil? %>
				<h1 style="letter-spacing: 3px;">
				  <%= @word = Game.generate_blanks(@game.word).join %>
				</h1>
			  <% else %>
				<h1 style="letter-spacing: 3px;"><%= @word %></h1>
			  <% end %>
				
			  <% @mistake ||= 0 %>
				
			  <% if @mistake < 8 && @word.downcase != @game.word %>
			    <%= form_tag input_path, method: :post do %>
				  <%= text_field_tag :input, nil, placeholder: "Enter a letter..", style:"height: 34px;" %>
				  <%= hidden_field_tag :game_id, @game.id %>
				  <%= hidden_field_tag :word, @word %>
				  <%= hidden_field_tag :mistake, @mistake %>
				  <%= hidden_field_tag :wrong, @wrong %>

				  <%= submit_tag "Go", class:"btn btn-danger" %>
				<% end %>
			  <% end %>
			  
			  <div style="margin-top: 20px;">
			    <%= label_tag :wrong_attempts %>
			    <%= text_field_tag :wrong, @wrong.split("").join(", "), disabled: true, class:"form-control", style: "width: 200px;" %>
			  </div><br>
				
			  <div style="margin-top: 50px; margin-bottom: 200px;">
			    <% if @mistake >= 8 %>
			      <h3>Correct Answer: <%= @game.word.upcase %></h3>
				  <h2 style="color: red;"><%=  'Game Over...' %></h2>
			    <% elsif @word.downcase == @game.word %>
				  <h2><%=  'You have won!' %></h2>
			    <% end %>
			  </div>

			<% end %>
		</div>
  	</div>

    <div class="col-md-4">
    	<% case @mistake %>
    	<% when 0 %>
		<%= image_tag "0.png", style:"max-width: 100%; max-height: 100%;" %>
		<% when 1 %>
		<%= image_tag "1.png", style:"max-width: 100%; max-height: 100%;" %>
		<% when 2 %>
		<%= image_tag "2.png", style:"max-width: 100%; max-height: 100%;" %>
		<% when 3 %>
		<%= image_tag "3.png", style:"max-width: 100%; max-height: 100%;" %>
		<% when 4 %>
		<%= image_tag "4.png", style:"max-width: 100%; max-height: 100%;" %>
		<% when 5 %>
		<%= image_tag "5.png", style:"max-width: 100%; max-height: 100%;" %>
		<% when 6 %>
		<%= image_tag "6.png", style:"max-width: 100%; max-height: 100%;" %>
		<% when 7 %>
		<%= image_tag "7.png", style:"max-width: 100%; max-height: 100%;" %>
		<% else %>
		<%= image_tag "8.png", style:"max-width: 100%; max-height: 100%;" %>
		<% end %>
    </div>
  </div>  
</div>


</div>

app/views/users/new.html.erb
  <div class="wrapper">
    <div class="form-signin">       
      <h2 class="form-signin-heading">Play Hangman</h2>
      
      <%= form_for @user do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>      

      <%= f.label :email %>
      <%= f.text_field :email, class:"form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class:"form-control" %>
      
      <%= f.submit "Sign Up", class:"btn btn-lg btn-primary btn-block" %> 

    <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<h1>User profile</h1>

<% if Relationship.friends?(current_user, params[:id]) %>
	<div>
		<%= button_to "Unfriend", user_relationship_path(params[:id]), method: :delete %>
	</div>
<% else %>
	<div>
		<%= button_to "Add friend", user_relationships_path(params[:id]), method: :post %>
	</div>
<% end %>

app/views/welcome/_friends.html.erb
      <div class="panel panel-primary" style="margin-top: 10px;">
        <div class="panel-heading">
          <h3 class="panel-title">Friend List</h3>
        </div>
        <div class="panel-body">
	      <table class="table">
	      	<tbody>
	        <% current_user.friends.each do |friend| %>
	        <tr>
	          <td><%= friend.name %></td>
	          	<% if current_user.role == "owner" && !current_user.room.nil? %>
	          		<% if @room.visitor.nil? %>
		          		<%= form_tag room_path(current_user.room.id), method: :patch, class:"invite" do %>
						<%= hidden_field_tag :friend_id, friend.id %>
						<td><%= submit_tag "Invite", class:"btn btn-danger" %></td>
						<% end %>
        			<% end %>
        		<% end %>
			</tr>
			  <% end %>
			</tbody>
	      </table>          

	      </ul>
        </div>
      </div> 

app/views/welcome/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Hangman</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Profile", user_path(current_user.id) %></li>
      </ul>
      <div class="navbar-form navbar-left">
        <%= form_tag search_path, method: :post do %>
          <div class="form-group">
            <%= text_field_tag :search_name, params[:search_name], placeholder: "Search user", class:"form-control" %>
          </div>
          <%= submit_tag "Search", class:"btn btn-default" %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Sign Out", sign_out_path, method: :delete %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<div class="p-3 mb-2 bg-light text-dark">

<%= render partial: '/welcome/navbar' %>


<div class="container", style="background: white; width: 90%; height: 100%;">
  <div class="row">
    <div class="col-sm-8 col-md-offset-1">
        <h1 style="font-color: black; font-weight: 300; text-align: left; margin-left: 30px;">Welcome, <%= @user.name %></h1>
		
        <% if @users %>
			<table class="table">
			  <thead>
			    <tr>
			      <th scope="col">ID</th>
			      <th scope="col">Name</th>
			      <th scope="col"></th>
			    </tr>
			  </thead>
			  <tbody>
				<% @users.each do |user| %>
				    <tr>
				      <td scope="row"><%= user.id %></td>
				      <td><%= user.name %></td>

				<% if Relationship.friends?(current_user, user.id) %>
					<% rel = Relationship.find_by(user_id: current_user.id, friend_id: user.id) %>
					  <td>
						<%= button_to "Unfriend", user_relationship_path(user.id, rel.id), method: :delete, class:"btn btn-danger" %>
					  </td>
				<% else %>
					  <td>
						<%= button_to "Add friend", user_relationships_path(user.id), method: :post, class:"btn btn-danger" %>
					  </td>
				<% end %>
				    </tr>
				<% end %>
			  </tbody>
			</table>
		<% end %>

	    <div style="margin-left: 30px;">
			<% if @user.room.nil? %>
				<%= button_to "Create Room", rooms_path, method: :post, class:"btn btn-danger" %>
			<% else %>
				<%= button_to "Enter Room", room_path(@room.id), method: :get, class:"btn btn-danger", style:"float: left;" %>

				<%= button_to "Leave Room", room_path(@user.room.id), method: :delete, class:"btn btn-danger", style:"float: left; margin-left: 10px;" %>
			<% end %>
	    </div>

	    <div style="margin-top: 20px;">
	    	<%= image_tag "hangman.png", style:"max-width: 100%; max-height: 100%;" %>
	    </div>
    </div>

    <div class="col-sm-3">
		<%= render partial: '/welcome/friends' %>
    </div>
  </div>
</div>


</div>